name: qprimer-designer
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  # Bioinformatics tools
  - viennarna>=2.6
  - bowtie2>=2.5
  - sam2pairwise
  - mafft>=7.5
  # Workflow
  - snakemake>=9.0
  # For pip install
  - pip
